name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
include: package:flutter_lints/flutter.yaml

version: 1.0.0+1

environment:
  sdk: "^3.8.1"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true  # This ensures you can use Material Design widgets
